import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import LanguageToggle from "@/components/LanguageToggle/LanguageToggle";
import { LanguageProvider } from "@/components/i18n/LanguageProvider";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html>
      <body>
        <LanguageProvider>
          <header style={{ borderBottom: "1px solid rgba(0,0,0,0.08)" }}>
            <nav
              style={{
                maxWidth: 980,
                margin: "0 auto",
                padding: "14px 18px",
                display: "flex",
                alignItems: "center",
                justifyContent: "space-between",
                gap: 12,
              }}
            >
              <Link href="/" style={{ textDecoration: "none", color: "inherit", fontWeight: 800 }}>
                Matryoshka NZ
              </Link>

              <LanguageToggle />
            </nav>
          </header>

          {children}
        </LanguageProvider>
      </body>
    </html>
  );
}

